### ISSUE TITLE
uninitialized constant Poise::Backports::VERIFY_PATH

### ISSUE THREAD

**Issue by gretel** [poise/poise-monit#10]
```
...
Chef Client, version 12.6.0
poise-languages (1.3.2)
poise-service (1.1.0)
poise-monit (1.0.2)
...
```

``` ================================================================================
           Error executing action `enable` on resource 'monit[monit]'
           ================================================================================

           NameError
           ---------
           uninitialized constant Poise::Backports::VERIFY_PATH

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:144:in `block in write_config'
           /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:138:in `write_config'
           /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:48:in `block in action_enable'
           /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'
           /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `subcontext_block'
           /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:67:in `notifying_block'
           /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:41:in `action_enable'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/whatever/recipes/_monit.rb

            14: monit 'monit' do
            15:   daemon_interval  node['graphite']['monit']['daemon_interval']
            16:   # event_slots 0
            17:   httpd_password node['graphite']['monit']['http_password']
            18:   httpd_port  node['graphite']['monit']['http_port']
            19:   httpd_username  node['graphite']['monit']['http_username']
            20:   provider :system
            21: end
            22:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/whatever/recipes/_monit.rb:14:in `from_file'

           monit("monit") do
             provider PoiseMonit::MonitProviders::System
             action [:enable]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             subresources [monit_config[mailconfig]]
             declared_type :monit
             cookbook_name "whatever"
             recipe_name "_monit"
             daemon_interval 60
             httpd_password "bar"
             httpd_port 2812
             httpd_username "foo"
             service_name "monit"
             path "/etc/monit"
             var_path "/var/lib/monit"
             config_content "# Generated by Chef for monit[monit]\n\n\nSET PIDFILE /var/run/monit_real.pid\n\nSET LOGFILE /var/log/monit.log\n\nSET IDFILE /var/lib/monit/id\nSET STATEFILE /var/lib/monit/state\nSET EVENTQUEUE BASEDIR /var/lib/monit/events SLOTS 100\n\nSET HTTPD PORT 2812\n  ALLOW foo:bar\n\nINCLUDE /etc/monit/conf.d/*\n"
             config_cookbook "poise-monit"
             pidfile "/var/run/monit_real.pid"
             logfile "/var/log/monit.log"
             event_slots 100
           end
```

**Comment by coderanger** [comment]
Are you trying to run a pre-release version? This isn't in the latest release. To run the current pre-release you'll need master or Poise too but I'm in the middle of gutting my multi-project testing system so stuff is a little broken right now.
