### ISSUE TITLE
poise-monit throws Chef::Resource::File::Verification for seemingly valid configuration

### ISSUE THREAD

**Issue by rkeiii** [poise/poise-monit#16]
I tried manually running the "monit -t" command against the suggested configuration. The monit -t works on /etc/monit/monitrc but fails when run against the individual file /etc/monit/conf.d/pgbouncer.conf. If I take the file ocntent suggested by the poise-monit cookbook and manually put it in /etc/monit/conf.d/pgbouncer.conf monit starts successfully.

The monit -t command appears to get hung up on the "depends on" line in pgbouncer.conf. When run against the individual pgbouncer.conf monit -t complains that it is not aware of the dependant service's existence. 

Not sure if this is a bug or if I'm doing doing something terribly wrong. chef-client output follows.

```
Recipe: poise-monit::default
  * monit[monit] action enable
    * poise_languages_static[/opt/monit-5.17.1] action install
      * poise_archive[/var/chef/cache/monit-5.17.1-linux-x64.tar.gz] action nothing (skipped due to action :nothing)
      * remote_file[/var/chef/cache/monit-5.17.1-linux-x64.tar.gz] action create (up to date)
      * directory[/opt/monit-5.17.1] action create (up to date)
       (up to date)
    * directory[/etc/monit] action create
      - create new directory /etc/monit
      - change mode from '' to '0700'
    * directory[/etc/monit/conf.d] action create
      - create new directory /etc/monit/conf.d
      - change mode from '' to '0700'
    * directory[/var/lib/monit] action create (up to date)
    * directory[/var/lib/monit/events] action create (up to date)
    * file[/etc/monit/monitrc] action create
      - create new file /etc/monit/monitrc
      - update content in file /etc/monit/monitrc from none to e26ac0
      --- /etc/monit/monitrc    2016-07-27 16:38:06.628943441 -0700
      +++ /etc/monit/.chef-monitrc20160727-19238-13o2ufi    2016-07-27 16:38:06.612943181 -0700
      @@ -1 +1,16 @@
      +# Generated by Chef for monit[monit]
      +
      +
      +SET PIDFILE /var/run/monit_real.pid
      +
      +SET LOGFILE /var/log/monit.log
      +
      +SET IDFILE /var/lib/monit/id
      +SET STATEFILE /var/lib/monit/state
      +SET EVENTQUEUE BASEDIR /var/lib/monit/events SLOTS 100
      +
      +SET HTTPD UNIXSOCKET /var/run/monit.sock
      +  ALLOW 0.0.0.0/0
      +
      +INCLUDE /etc/monit/conf.d/*
      - change mode from '' to '0600'
    * monit[monit] action reload
      * poise_service[monit] action reload
        * service[monit] action reload
          - reload service service[monit]


    * poise_service[monit] action enable
      * template[/etc/init/monit.conf] action create
        - update content in file /etc/init/monit.conf from 0ad796 to fef3af
        --- /etc/init/monit.conf    2016-07-27 16:36:52.735742397 -0700
        +++ /etc/init/.chef-monit.conf20160727-19238-tsegx2 2016-07-27 16:38:07.164952154 -0700
        @@ -13,5 +13,5 @@
         kill signal TERM
         reload signal HUP

        -exec /opt/monit-5.17.1/bin/monit -c /etc/monit/monitrc -I -d 60
        +exec /opt/monit-5.17.1/bin/monit -c /etc/monit/monitrc -I -d 120
      * service[monit] action enable (up to date)
      * service[monit] action start (up to date)


Recipe: cookbook_name::monit_base
  * apt_package[monit] action remove (up to date)
  * monit[monit] action enable
    * poise_languages_static[/opt/monit-5.17.1] action install
      * poise_archive[/var/chef/cache/monit-5.17.1-linux-x64.tar.gz] action nothing (skipped due to action :nothing)
      * remote_file[/var/chef/cache/monit-5.17.1-linux-x64.tar.gz] action create (up to date)
      * directory[/opt/monit-5.17.1] action create (up to date)
       (up to date)
    * directory[/etc/monit] action create (up to date)
    * directory[/etc/monit/conf.d] action create (up to date)
    * directory[/var/lib/monit] action create (up to date)
    * directory[/var/lib/monit/events] action create (up to date)
    * file[/etc/monit/monitrc] action create
      - update content in file /etc/monit/monitrc from e26ac0 to f7a3a7
      --- /etc/monit/monitrc    2016-07-27 16:38:06.612943181 -0700
      +++ /etc/monit/.chef-monitrc20160727-19238-51kily 2016-07-27 16:38:07.568958717 -0700
      @@ -7,10 +7,8 @@

       SET IDFILE /var/lib/monit/id
       SET STATEFILE /var/lib/monit/state
      -SET EVENTQUEUE BASEDIR /var/lib/monit/events SLOTS 100
      +SET EVENTQUEUE BASEDIR /var/lib/monit/events SLOTS 1000

      -SET HTTPD UNIXSOCKET /var/run/monit.sock
      -  ALLOW 0.0.0.0/0

       INCLUDE /etc/monit/conf.d/*
    * monit[monit] action reload
      * poise_service[monit] action reload
        * service[monit] action reload
          - reload service service[monit]


    * poise_service[monit] action enable
      * template[/etc/init/monit.conf] action create
        - update content in file /etc/init/monit.conf from fef3af to 0ad796
        --- /etc/init/monit.conf    2016-07-27 16:38:07.164952154 -0700
        +++ /etc/init/.chef-monit.conf20160727-19238-n9teld 2016-07-27 16:38:08.144968083 -0700
        @@ -13,5 +13,5 @@
         kill signal TERM
         reload signal HUP

        -exec /opt/monit-5.17.1/bin/monit -c /etc/monit/monitrc -I -d 120
        +exec /opt/monit-5.17.1/bin/monit -c /etc/monit/monitrc -I -d 60
      * service[monit] action enable (up to date)
      * service[monit] action start (up to date)


  * execute[cat /etc/ssl/certs/WILDCARD.qa.domain.tld.combined.crt /etc/ssl/private/WILDCARD.qa.domain.tld.key > /etc/monit/monit.pem] action run
    - execute cat /etc/ssl/certs/WILDCARD.qa.domain.tld.combined.crt /etc/ssl/private/WILDCARD.qa.domain.tld.key > /etc/monit/monit.pem
  * file[/etc/monit/monit.pem] action create
    - change mode from '0644' to '0600'
  * monit_config[baseconfig] action create
    * file[/etc/monit/conf.d/baseconfig.conf] action create
      - create new file /etc/monit/conf.d/baseconfig.conf
      - update content in file /etc/monit/conf.d/baseconfig.conf from none to 9b2d75
      --- /etc/monit/conf.d/baseconfig.conf 2016-07-27 16:38:08.280970293 -0700
      +++ /etc/monit/conf.d/.chef-baseconfig.conf20160727-19238-1q0x35o 2016-07-27 16:38:08.260969968 -0700
      @@ -1 +1,11 @@
      +set alert sysadmin@domain.tld only on { timeout }
      +
      +set httpd port 2812
      +
      +  allow @sysadmin
      +  allow @monit-admin-qa
      +  allow @users readonly
      +
      +  ssl enable
      +  pemfile /etc/monit/monit.pem
      - change mode from '' to '0600'
    * monit[monit] action reload
      * poise_service[monit] action reload
        * service[monit] action reload
          - reload service service[monit]



  * directory[/etc/monit] action create
    - change mode from '0700' to '0755'
  * execute[cat /etc/ssl/certs/WILDCARD.qa.domain.tld.combined.crt /etc/ssl/private/WILDCARD.qa.domain.tld.key > /etc/monit/monit.pem] action run (skipped due to not_if)
  * file[/etc/monit/monit.pem] action create (up to date)
Recipe: cookbook_name::monit_haproxy_and_pgbouncer
  * apt_package[postgresql-client] action install (up to date)
  * monit_check[pgbouncer] action create
    * file[/etc/monit/conf.d/pgbouncer.conf] action create

      ================================================================================
      Error executing action `create` on resource 'file[/etc/monit/conf.d/pgbouncer.conf]'
      ================================================================================

      Chef::Exceptions::ValidationFailed
      ----------------------------------
      Proposed content for /etc/monit/conf.d/pgbouncer.conf failed verification #<Chef::Resource::File::Verification:0x00000006181e00>

      Cookbook Trace:
      ---------------
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
      /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
      /var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit_config.rb:72:in `action_create'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit_config.rb

       90:           file new_resource.path do
       91:             content new_resource.content
       92:             group new_resource.parent.group if new_resource.parent.group
       93:             mode '600'
       94:             notifies :reload, new_resource.parent, :immediately
       95:             owner new_resource.parent.owner if new_resource.parent.owner
       96:             verify "#{new_resource.parent.monit_binary} -t -c #{Poise::Backports::VERIFY_PATH}" if defined?(verify)
       97:           end
       98:         end

      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit_config.rb:90:in `create_config'

      file("/etc/monit/conf.d/pgbouncer.conf") do
        action [:create]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :file
        cookbook_name "cookbook_name"
        content "CHECK PROGRAM pgbouncer path \"/usr/bin/psql --user cookbook_name --host localhost --port 6432 --command 'SELECT 1;' --quiet bksdb\" timeout 30 seconds\n  start program = \"/usr/bin/docker start qa-pgbouncer\"\n  stop program = \"/usr/bin/docker stop qa-pgbouncer\"\n  if status != 0 for 2 cycles then restart\n  if 60 restarts within 60 cycles then unmonitor\n  group db\n  depends on haproxy\n"
        mode "600"
        path "/etc/monit/conf.d/pgbouncer.conf"
        verifications [#<Chef::Resource::File::Verification:0x00000006181e00 @command_opts={}, @command="/opt/monit-5.17.1/bin/monit -t -c %{path}", @block=nil, @parent_resource=<file[/etc/monit/conf.d/pgbouncer.conf] @name: "/etc/monit/conf.d/pgbouncer.conf" @noop: nil @before: nil @params: nil @provider: nil @allowed_actions: [:nothing, :create, :delete, :touch, :create_if_missing] @action: [:create] @updated: false @updated_by_last_action: false @supports: {} @ignore_failure: false @retries: 0 @retry_delay: 2 @source_line: "/var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit_config.rb:90:in `create_config'" @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @sensitive: false @declared_type: :file @cookbook_name: "cookbook_name" @recipe_name: nil @owner: nil @group: nil @content: "CHECK PROGRAM pgbouncer path \"/usr/bin/psql --user cookbook_name --host localhost --port 6432 --command 'SELECT 1;' --quiet bksdb\" timeout 30 seconds\n  start program = \"/usr/bin/docker start qa-pgbouncer\"\n  stop program = \"/usr/bin/docker stop qa-pgbouncer\"\n  if status != 0 for 2 cycles then restart\n  if 60 restarts within 60 cycles then unmonitor\n  group db\n  depends on haproxy\n" @mode: "600" @path: "/etc/monit/conf.d/pgbouncer.conf" @verifications: [...]>>]
      end

      Platform:
      ---------
      x86_64-linux


    ================================================================================
    Error executing action `create` on resource 'monit_check[pgbouncer]'
    ================================================================================

    Chef::Exceptions::ValidationFailed
    ----------------------------------
    file[/etc/monit/conf.d/pgbouncer.conf] (/var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit_config.rb line 90) had an error: Chef::Exceptions::ValidationFailed: Proposed content for /etc/monit/conf.d/pgbouncer.conf failed verification #<Chef::Resource::File::Verification:0x00000006181e00>

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
    /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
    /var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit_config.rb:72:in `action_create'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/cookbook_name/recipes/monit_haproxy_and_pgbouncer.rb

     19:   monit_check service[:name] do
     20:     check ['if status != 0 for 2 cycles then restart',
     21:            'if 60 restarts within 60 cycles then unmonitor']
     22:     check_type 'program'
     23:     with  'path "/usr/bin/psql --user cookbook_name --host localhost --port ' + service[:port].to_s + ' --command \'SELECT 1;\' --quiet bksdb" timeout 30 seconds'
     24:     start_program '/usr/bin/docker start ' + node.chef_environment + '-' + service[:name]
     25:     stop_program '/usr/bin/docker stop ' + node.chef_environment + '-' + service[:name]
     26:     extra service[:extra]
     27:   end
     28: 

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/cookbook_name/recipes/monit_haproxy_and_pgbouncer.rb:19:in `block in from_file'

    monit_check("pgbouncer") do
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :monit_check
      cookbook_name "cookbook_name"
      recipe_name "monit_haproxy_and_pgbouncer"
      check ["if status != 0 for 2 cycles then restart", "if 60 restarts within 60 cycles then unmonitor"]
      check_type "program"
      with "path \"/usr/bin/psql --user cookbook_name --host localhost --port 6432 --command 'SELECT 1;' --quiet bksdb\" timeout 30 seconds"
      start_program "/usr/bin/docker start qa-pgbouncer"
      stop_program "/usr/bin/docker stop qa-pgbouncer"
      extra ["group db", "depends on haproxy"]
      parent monit[monit]
      config_name "pgbouncer"
      path "/etc/monit/conf.d/pgbouncer.conf"
      content "CHECK PROGRAM pgbouncer path \"/usr/bin/psql --user cookbook_name --host localhost --port 6432 --command 'SELECT 1;' --quiet bksdb\" timeout 30 seconds\n  start program = \"/usr/bin/docker start qa-pgbouncer\"\n  stop program = \"/usr/bin/docker stop qa-pgbouncer\"\n  if status != 0 for 2 cycles then restart\n  if 60 restarts within 60 cycles then unmonitor\n  group db\n  depends on haproxy\n"
      cookbook "poise-monit"
    end

    Platform:
    ---------
    x86_64-linux

  * poise_service[monit] action restart
    * service[monit] action stop
      - stop service service[monit]
    * service[monit] action start
      - start service service[monit]

  * poise_service[monit] action restart
    * service[monit] action stop
      - stop service service[monit]
    * service[monit] action start
      - start service service[monit]


Running handlers:
[2016-07-27T16:38:10-07:00] ERROR: Running exception handlers
Running handlers complete
[2016-07-27T16:38:10-07:00] ERROR: Exception handlers complete
Chef Client failed. 46 resources updated in 51 seconds
[2016-07-27T16:38:10-07:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-07-27T16:38:10-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-07-27T16:38:10-07:00] ERROR: monit_check[pgbouncer] (cookbook_name::monit_haproxy_and_pgbouncer line 19) had an error: Chef::Exceptions::ValidationFailed: file[/etc/monit/conf.d/pgbouncer.conf] (/var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit_config.rb line 90) had an error: Chef::Exceptions::ValidationFailed: Proposed content for /etc/monit/conf.d/pgbouncer.conf failed verification #<Chef::Resource::File::Verification:0x00000006181e00>
[2016-07-27T16:38:10-07:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by coderanger** [comment]
The way the Chef file validation system works, it checks each file in isolation. In this case you probably want to put both the related chunks in a single config file :)

**Comment by rkeiii** [comment]
Thanks for the reply. It looks to me like I'll need to switch away from monit_check and use monit_config instead, is that correct?

**Comment by coderanger** [comment]
Yeah, for something using multi-check features like dependencies the high-level abstractions are going to break down.

**Comment by rkeiii** [comment]
Understood, thanks for the pointers. :)

**Comment by coderanger** [comment]
It does raise the question as to if I should add flags to all the resources to disable verification if you want to do something fancy, but I think I'll wait until a few more cases like this show up before I do that.

**Comment by rkeiii** [comment]
I'm guessing you're already aware  running monit -t on /etc/monit/monitrc will check all the dependency files for validity as well (or so it appears from the noisy output mode). Just thought I'd mention it.

**Comment by coderanger** [comment]
The per-file verification is part of how Chef works, the goal is avoid ever putting a badly formatted file in place at all. The runs the check against the rendered tempfile instead. It could be done in-place but that would mean building a transactional layer to put the old file content back and yadayada.
