### ISSUE TITLE
undefined method `gsub' for nil:NilClass

### ISSUE THREAD

**Issue by gretel** [poise/poise-monit#2]
using `chef-12.6.0` on `ubuntu-14.04`:

```
gem 'halite'
gem 'poise-monit', github: 'poise/poise-monit'
```

gives me the following error:

```
       Recipe: poise-monit::default
         * monit[monit] action enable
       ================================================================================
       Error executing action `enable` on resource 'monit[monit]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `gsub' for nil:NilClass

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/static/mixin.rb:99:in `static_version'
       /tmp/kitchen/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/static/mixin.rb:81:in `default_inversion_options'
       /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/inversion.rb:278:in `block in inversion_options'
           /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/inversion.rb:271:in `tap'
           /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/inversion.rb:271:in `inversion_options'

           /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/inversion.rb:354:in `provides?'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/poise-monit/recipes/default.rb

            17: monit 'monit' do
            18:   node['poise-monit']['recipe'].each do |key, value|
            19:     # Skip nils, use false if you want to disable something.
            20:     send(key, value) unless value.nil?
            21:   end
            22: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/poise-monit/recipes/default.rb:17:in `from_file'

           monit("monit") do
             action [:enable]
             retries 0
         retry_delay 2
         default_guard_interpreter :default
         declared_type :monit

             recipe_name "default"
       end
```

**Comment by coderanger** [comment]
You'll need `poise-languages` and probably `poise` itself from master too if you want to run this before release. Or wait about three hours while I write a bunch of changelogs and make git tags :)

**Comment by gretel** [comment]
ah, i see. my weekend just started.. going to enjoy your release on monday. regards
