### ISSUE TITLE
monit_service[x] fails for chef 14

### ISSUE THREAD

**Issue by Aergonus** [poise/poise-monit#31]
https://github.com/chef/chef/blob/master/lib/chef/mixin/shell_out.rb#L73-L84 now adds the `timeout` property by default which is hard-defined to throw `NoMethodError` [here](https://github.com/poise/poise-monit/blob/master/lib/poise_monit/resources/monit_service.rb#L60-L65)

```
       Running handlers:
       [2019-03-18T12:17:39-04:00] ERROR: Running exception handlers
       Running handlers complete
       [2019-03-18T12:17:39-04:00] ERROR: Exception handlers complete
       Chef Client failed. 6 resources updated in 05 seconds
       [2019-03-18T12:17:39-04:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2019-03-18T12:17:39-04:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2019-03-18T12:17:39-04:00] DEBUG: NoMethodError: XXX_service[XXX] (XXX::XXX_unix line 31) had an error: NoMethodError: poise_service[XXX] (/tmp/kitchen/cache/cookbooks/XXX/recipes/XXX_unix.rb line 31) had an error: NoMethodError: monit_service[XXX] (/tmp/kitchen/cache/cookbooks/XXX/recipes/XXX_unix.rb line 31) had an error: NoMethodError: Property timeout is not supported on monit_service
       /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit_service.rb:63:in `block (2 levels) in <class:Resource>'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/mixin/shell_out.rb:147:in `maybe_add_timeout'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/mixin/shell_out.rb:110:in `shell_out'
       /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/utils/shell_out.rb:78:in `poise_shell_out'
       /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit_service.rb:179:in `monit_shell_out!'
       /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit_service.rb:165:in `find_monit_status'
       /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit_service.rb:94:in `block in load_current_resource'
       /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit_service.rb:86:in `tap'
       /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit_service.rb:86:in `load_current_resource'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/provider.rb:165:in `run_action'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/resource.rb:578:in `run_action'
       /tmp/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_providers/base.rb:124:in `block in enable_service'
       /tmp/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_providers/base.rb:136:in `notify_if_service'
       /tmp/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_providers/base.rb:123:in `enable_service'
       /tmp/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_providers/base.rb:60:in `action_enable'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/provider.rb:182:in `run_action'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/resource.rb:578:in `run_action'
       /tmp/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_mixin.rb:89:in `block in action_enable'
       /tmp/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_mixin.rb:154:in `notify_if_service'
       /tmp/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_mixin.rb:88:in `action_enable'
       /tmp/kitchen/cache/cookbooks/XXX/libraries/XXX_service.rb:67:in `action_enable'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/provider.rb:182:in `run_action'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/resource.rb:578:in `run_action'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/runner.rb:70:in `run_action'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/runner.rb:98:in `block (2 levels) in converge'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/runner.rb:98:in `each'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/runner.rb:98:in `block in converge'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/runner.rb:97:in `converge'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/client.rb:720:in `block in converge'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/client.rb:715:in `catch'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/client.rb:715:in `converge'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/client.rb:754:in `converge_and_save'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/client.rb:286:in `run'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/application.rb:279:in `block in run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/local_mode.rb:44:in `with_server_connectivity'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/application.rb:261:in `run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/application/client.rb:440:in `run_application'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/application.rb:66:in `run'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/bin/chef-client:25:in `<top (required)>'
       /opt/chef/bin/chef-client:74:in `load'
       /opt/chef/bin/chef-client:74:in `<main>'
```

**Comment by Aergonus** [comment]
:)

**Comment by coderanger** [comment]
There is a roughly 0% chance of this getting fixed, sorry.
