### ISSUE TITLE
`block in create_directory'

### ISSUE THREAD

**Issue by gretel** [poise/poise-monit#5]
`chef-12.6` on `ubuntu-12.04`:

```
       /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:92:in `block in create_directory'

       /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:42:in `block in action_enable'
       /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'
       /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `subcontext_block'

       /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:41:in `action_enable'
       /opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
       /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'

       /opt/chef/bin/chef-client:54:in `<main>'
       /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:92:in `block in create_directory'
       /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:91:in `create_directory'
       /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:42:in `block in action_enable'
       /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'
       /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `subcontext_block'

       /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:41:in `action_enable'

       /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
```

**Comment by coderanger** [comment]
You included the stack trace but not the actual exception?

**Comment by coderanger** [comment]
Guessing it's either "parent directory does not exist" or a permissions problem?

**Comment by gretel** [comment]
doh, going to add the exception, sorry. seems to work fine so far though

**Comment by gretel** [comment]
```
   * monit[monit] action enable
     * file[/etc/init.d/monit] action nothing (skipped due to action :nothing)
     * apt_package[monit] action install (up to date)
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:92:in `block in create_directory'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:91:in `create_directory'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:42:in `block in action_enable'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `subcontext_block'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:67:in `notifying_block'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:41:in `action_enable'
 /opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
 /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
 /opt/chef/bin/chef-client:54:in `load'
 /opt/chef/bin/chef-client:54:in `<main>'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:92:in `block in create_directory'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:91:in `create_directory'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:42:in `block in action_enable'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `subcontext_block'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:67:in `notifying_block'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:41:in `action_enable'
 /opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
 /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
 /opt/chef/bin/chef-client:54:in `load'
 /opt/chef/bin/chef-client:54:in `<main>'
 [2016-01-14T12:27:09+00:00] WARN: /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:92:in `block in create_directory': property group is declared in both directory[/etc/monit] and #<PoiseMonit::MonitProviders::System:0x000000057edec0>. Use new_resource.group instead. At /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:92:in `block in create_directory'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:101:in `block in create_confd_directory'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:100:in `create_confd_directory'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:43:in `block in action_enable'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `subcontext_block'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:67:in `notifying_block'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:41:in `action_enable'
 /opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
 /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
 /opt/chef/bin/chef-client:54:in `load'
 /opt/chef/bin/chef-client:54:in `<main>'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:101:in `block in create_confd_directory'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:100:in `create_confd_directory'
 in action_enable'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `subcontext_block'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:67:in `notifying_block'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:41:in `action_enable'
 /opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
 /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
 /opt/chef/bin/chef-client:54:in `load'
 /opt/chef/bin/chef-client:54:in `<main>'
 [2016-01-14T12:27:09+00:00] WARN: /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:101:in `block in create_confd_directory': property group is declared in both directory[/etc/monit/conf.d] and #<PoiseMonit::MonitProviders::System:0x000000057edec0>. Use new_resource.group instead. At /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:101:in `block in create_confd_directory'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:111:in `block in create_var_directory'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:110:in `create_var_directory'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:44:in `block in action_enable'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `subcontext_block'

 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:41:in `action_enable'

 /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
 /opt/chef/bin/chef-client:54:in `load'
 /opt/chef/bin/chef-client:54:in `<main>'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:111:in `block in create_var_directory'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:110:in `create_var_directory'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:44:in `block in action_enable'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `subcontext_block'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:67:in `notifying_block'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:41:in `action_enable'

 /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
 /opt/chef/bin/chef-client:54:in `load'
 /opt/chef/bin/chef-client:54:in `<main>'
 [2016-01-14T12:27:09+00:00] WARN: /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:111:in `block in create_var_directory': property group is declared in both directory[/var/lib/monit] and #<PoiseMonit::MonitProviders::System:0x000000057edec0>. Use new_resource.group instead. At /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:111:in `block in create_var_directory'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:120:in `block in create_events_directory'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:119:in `create_events_directory'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:45:in `block in action_enable'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'

 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:67:in `notifying_block'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:41:in `action_enable'
 /opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'

 /opt/chef/bin/chef-client:54:in `load'

 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:120:in `block in create_events_directory'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:119:in `create_events_directory'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:45:in `block in action_enable'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `subcontext_block'

 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:41:in `action_enable'
 /opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'

 /opt/chef/bin/chef-client:54:in `load'

 [2016-01-14T12:27:09+00:00] WARN: /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:120:in `block in create_events_directory': property group is declared in both directory[/var/lib/monit/events] and #<PoiseMonit::MonitProviders::System:0x000000057edec0>. Use new_resource.group instead. At /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:120:in `block in create_events_directory'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:130:in `block in write_password_state'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:128:in `write_password_state'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:47:in `block in action_enable'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'

 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:67:in `notifying_block'

 /opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
 /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'

 /opt/chef/bin/chef-client:54:in `<main>'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:130:in `block in write_password_state'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:128:in `write_password_state'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:47:in `block in action_enable'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `subcontext_block'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:67:in `notifying_block'

 /opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
 /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'

 /opt/chef/bin/chef-client:54:in `<main>'
 [2016-01-14T12:27:09+00:00] WARN: /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:130:in `block in write_password_state': property group is declared in both file[/var/lib/monit/.cli-password] and #<PoiseMonit::MonitProviders::System:0x000000057edec0>. Use new_resource.group instead. At /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:130:in `block in write_password_state'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:140:in `block in write_config'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:138:in `write_config'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:48:in `block in action_enable'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `subcontext_block'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:67:in `notifying_block'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:41:in `action_enable'
 /opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
 /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'

 /opt/chef/bin/chef-client:54:in `<main>'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:140:in `block in write_config'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:138:in `write_config'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:48:in `block in action_enable'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `subcontext_block'
 /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:67:in `notifying_block'
 /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:41:in `action_enable'
 /opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
 /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
 /opt/chef/bin/chef-client:54:in `load'
 /opt/chef/bin/chef-client:54:in `<main>'
 [2016-01-14T12:27:09+00:00] WARN: /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:140:in `block in write_config': property group is declared in both file[/etc/monit/monitrc] and #<PoiseMonit::MonitProviders::System:0x000000057edec0>. Use new_resource.group instead. At /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:140:in `block in write_config'
     * directory[/etc/monit] action create (up to date)
     * directory[/etc/monit/conf.d] action create (up to date)
     * directory[/var/lib/monit] action create (up to date)
     * directory[/var/lib/monit/events] action create (up to date)
     * file[/var/lib/monit/.cli-password] action create (up to date)
     * file[/etc/monit/monitrc] action create (up to date)
     * poise_service[monit] action enable
```

**Comment by coderanger** [comment]
Oh, it's the duplicate property warning. The warning is incorrect, you can ignore it. This is being tracked upstream in https://github.com/chef/chef/issues/4334, will hopefully be fixed in the next version of Chef.

**Comment by gretel** [comment]
@coderanger thanks for pointing that out.
